### ISSUE TITLE
Jenkins系列教程～录制计划（志愿者、讲师、社区合作持续招募中）

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-zh/jenkins-zh#345]
该视频教程录制记录，后续在下面的链接中维护：

https://hackmd.io/FZRmZU9FSrCNhWmVFEmGEA

注意事项：
* 录制时间尽量控制在10～15分钟，不可以超过20分钟
* 每个视频的主题要集中，要可以用一句话概述视频的主要内容
* 录制视频的讲师如果需要署名的话，请提供
* 如需领取视频录制任务，请在后面留言说明（选择哪个话题、计划开始和结束的时间）

# 志愿者
我们欢迎每一位有热情❤️的小伙伴加入我们的志愿者行列，需要志愿者做的事情包括（不仅限于）如下：
* 字幕制作
* 视频剪辑（工具为[Openshot](https://github.com/OpenShot/openshot-qt))
* 视频审核 - 讲师会把录制好的视频文件上传到[百度网盘](https://pan.baidu.com/)
* 图片设计 - [gimp](https://github.com/GNOME/gimp)

如果您希望加入志愿者的话，请在下面留言，并说明希望做的事情以及加入理由！！！

# 讲师
如果您热情于参与社区，如果您已经有一些 Jenkins 相关的经验、心得体会，如果您热衷于分享技术，那么请停下匆忙的脚步👣，加入我们的讲师团队吧！
心动不如行动，下面是我们的视频录制的流程：
* 选题，并在下面留言；我们鼓励您选择多个相关度很高的题目，例如：容器相关的。但是为了避免发生选题后时间难以保证产出的情况，建议先选择3以内的题目，完成后再次认领。
* 根据选题录制10～15分钟的视频，并上传[百度网盘](https://pan.baidu.com/)。如果某个题目相对较大，需要分成多起，确保符合我们的时长要求。
* 把录制好的视频发给我们的微信团队 review，根据反馈调整。推荐的录屏软件为：[OBS](https://obsproject.com/)
* 提供视频中您的署名
* 视频剪辑，通过后安排发布时间

# 社区合作
合作、共赢是我们推出公益性 Jenkins 视频教程的基础，贵社区的加入可以让更多的人因此获益。我们会将贵社区的 Logo 放在视频的片尾部分，图片文件请提交 Pull Request 到[视频剪辑项目仓库](https://github.com/jenkins-zh/jenkins-open-tutorial)中。
而您需要做的是，在贵社区的微信公众号平台上连续转载每一期的视频。

当前参与合作的社区有：[TesterHome](https://github.com/testerhome)、[Kubesphere](https://github.com/kubesphere/)、[DevOps中国](https://github.com/china-devopsdays)、云原生技术社区、禅道。

# 许可证
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

# 基础入门篇
* [ ] 064 Jenkins 社区概况
* [ ] 065 Jenkins 能做什么
* [x] 001 [Tomcat 中使用 Jenkins～macOS篇](https://www.bilibili.com/video/BV1UD4y1o7cm) @LinuxSuRen 
* [x] 002 [Tomcat 中使用 Jenkins～Windows篇](https://www.bilibili.com/video/BV1da4y1j7Sb) @lizhiposui
* [ ] 003 [Linux 中使用 Jenkins～rpm,dep]() @zhaoying818 
* [x] 004 [命令行直接启动 jenkins.war](https://www.bilibili.com/video/BV1xv411k7vX) @LinuxSuRen 
* [x] 005 [Jenkins自由风格的使用]() @LinuxSuRen 
* [x] 006 如何安装 Jenkins 插件 @LinuxSuRen #368 
* [x] 007 掌握 Jenkins 节点标签 @LinuxSuRen #382 
* [ ] 008 [Jenkins CLI 介绍]() @LinuxSuRen 

# 容器篇
* [ ] 067 容器技术简介
* [ ] 068 认识 Dockerfile
* [ ] 069 Docker 多阶段构建
* [ ] 070 Docker 多架构构建
* [ ] 071 其他容器技术 #448
* [x] 009 Docker 容器中安装 Jenkins @tjsooner #371 
* [x] 010 Kubernetes 集群中安装 Jenkins @tjsooner #387
* [ ] 011 [Kubernetes 集群中通过 helm 安装 Jenkins]() @tjsooner
* [ ] 012 [Kubernetes 集群运行 Jenkins 子节点]() @tjsooner
* [ ] 013 [Kubernetes 集群运行 Jenkins 子节点之 YAML 方式]() @tjsooner
* [ ] 014 基于 Jenkins 构建 Helm chart @perrypeng-peng
* [x] 059 阿里云 ECS 插件使用介绍 @zhongwandong

# 制品篇
* [ ] 072 常见的制品仓库
* [ ] 074 Jenkins 文件归档
* [ ] 075 Jenkins stash 和 unstash
* [ ] 076 存储制品到 minio

# 管理篇
* [ ] 015 [Jenkins 安装 SSH 节点]() @perrypeng-peng
* [x] 016 Jenkins 安装 JNLP 节点 @LinuxSuRen #383 
* [ ] 017 Jenkins 安装 Docker 节点 @LinuxSuRen #400
* [ ] 018 [Jenkins 性能调优之 JVM 参数]()
* [ ] 019 Jenkins 配置即代码 @LinuxSuRen #401
* [ ] 088 在 KubeSphere 3.x 中如何通过 CasC 配置 Jenkins
* [ ] 020 Jenkins 对接 LDAP #420
* [x] 080 Jenkins 对接 OIDC #417 @LinuxSuRen 
* [ ] 021 Jenkins 设置用户角色、权限
* [ ] 054 找回Jenkins管理员密码
* [ ] 062 Jenkins的主备模式
* [ ] 063 Jenkins & OpenTelemetry #428
* [ ] 081 Jenkins Operator 介绍
* [ ] 089 借助 Prometheus 实现对 Jenkins 的客观性

# 流水线篇
* [x] 022 Jenkins 流水线语法概述 @LinuxSuRen #376 
* [x] 053 Jenkins 流水线脚本生成器 @LinuxSuRen
* [ ] 083 Jenkins 参数化流水线 @LinuxSuRen
* [ ] 023 Jenkins 流水线 15 个常用 DSL @0N0thing #373 
* [ ] 024 [Jenkins 流水线之全局变量]() @LinuxSuRen
* [ ] 025 [Jenkins 流水线之处理 JSON 数据]() @LinuxSuRen
* [ ] 026 [Jenkins 流水线之等待输入]() @LinuxSuRen
* [ ] 027 [Jenkins 流水线之凭据的使用]() @LinuxSuRen
* [ ] 055 Jenkins 流水线之多任务互联 @LinuxSuRen #386
* [x] 028 [shared-library 概述]() @LinuxSuRen #398
* [ ] 029 [shared-library 在流水线中的基本使用]() @LinuxSuRen #409
* [ ] 030 [shared-library 在流水线中的高级使用]() @LinuxSuRen #410
* [ ] 031 [shared-library 避坑指南]() @LinuxSuRen #411
* [x] 032 [Jenkins 多分支流水线之 git]() @LinuxSuRen #412
* [ ] 033 [Jenkins 多分支流水线之 GitHub]() @LinuxSuRen #413
* [x] 034 [Jenkins 多分支流水线之 Gitlab]() @LinuxSuRen #414
* [ ] 082 Jenkins 流水线构建徽章（badge）
* [ ] 090 Webhook 触发 Jenkins 流水线 #452

# 案例篇（基于 Kubernetes）
* [x] 035 Jenkins 构建 Maven 项目
* [ ] 036 [Jenkins 构建 Maven 项目，缓存设置]()
* [x] 037 Jenkins 构建 Maven 项目，推送到 Nexus @LinuxSuRen 
* [ ] 038 Jenkins 构建 Golang 项目
* [ ] 039 [Jenkins 构建 Golang 项目，缓存设置]()
* [ ] 040 [Jenkins 构建 Gradle 项目]()
* [ ] 041 Jenkins 构建 Docker 镜像并推送到 Harbor
* [ ] 042 Jenkins 集成 Sonarqube
* [ ] 043 Jenkins 集成 Jira
* [ ] 044 Jenkins 集成 Harbor 安全漏洞扫描
* [ ] 056 如何限制 Jenkins 的构建 Pod 的带宽占用 @LinuxSuRen 
* [x] 057 如何在 Jenkins 中运行 Selenium 自动化测试 @LinuxSuRen #403
* [ ] 084 如何在 Jenkins 中运行 JMeter 实现性能自动化测试 @LinuxSuRen 
* [ ] 058 如何利用 Jenkins 构建并发布一个 Java  Web 应用
* [ ] 060 Jenkins 集成JFrog Artifactory 做依赖管理及制品管理 @liwei2151284 #406 
* [ ] 061 Jenkins 集成JFrog Xray 做依赖安全扫描  @liwei2151284 #407 
* [ ] 078 Jenkins 集成 Tekton
* [ ] 079 Jenkins 集成 Lighthouse @LinuxSuRen #421

# 持续交付
* [ ] 085 Flux 介绍
* [ ] 086 Argo CD 介绍
* [ ] 087 在 Jenkins 中借助 kustomize 发布 k8s 应用

# 定制篇
* [ ] 045 [介绍 Custom Jenkins WAR packager for Jenkins]()
* [ ] 046 [定制 Jenkins 发行版]()

# 插件开发篇
* [ ] 047 Jenkins 简体中文插件贡献指南
* [x] 048 [Jenkins 插件 helloworld]() @cizezsy
* [ ] 049 [Jenkins 插件，如何托管到官方社区]() @cizezsy
* [ ] 050 [Jenkins 插件，如何编写一个 DSL]() @cizezsy
* [ ] 051 [Jenkins 插件，了解插件的扩展机制]() @cizezsy
* [ ] 052 [Jenkins 插件，5个重要的扩展点]()

最大编号090

**Comment by tjsooner** [comment]
容器片～我可以来～赵淳

**Comment by LinuxSuRen** [comment]
非常欢迎 @tjsooner 加入我们，这个部分内容还会有其他的，如果您没有意见的话，就暂时把下面的部分分给您，后续再有新的还可以领取。非常感谢！
- Docker 容器中安装 Jenkins
- Kubernetes 集群中安装 Jenkins
- Kubernetes 集群中 通过 helm 安装 Jenkins
- Kubernetes 集群运行 Jenkins 子节点
- Kubernetes 集群运行 Jenkins 子节点之 YAML 方式

**Comment by LinuxSuRen** [comment]
macOS 下安装 [gimp](https://github.com/GNOME/gimp) 的命令为：`brew cask install gimp`

**Comment by zhaoying818** [comment]
Linux 中使用 Jenkins～rpm,dep 这个我认领

**Comment by LinuxSuRen** [comment]
以下为合作社区的转载记录：

| 编号 | TesterHome | Kubesphere | DevOps中国 | 云原生技术社区 | 禅道 |
|---|---|---|---|---|---|
|  001 | [done](https://mp.weixin.qq.com/s?__biz=MzAwNjEzMDUyNw==&mid=2650202079&idx=1&sn=65c7815883d41a1a8f067d70d31164c9&token=1879062946&lang=zh_CN#rd)  | [done](https://mp.weixin.qq.com/s?__biz=MzU1ODk5MzYwMw==&mid=2247484010&idx=2&sn=6007bf336ae92caa04993312fba1ac98&token=1879062946&lang=zh_CN#rd)  |   |   |   |
| 002 |   |   |   | [done](https://mp.weixin.qq.com/s/P0Y6flTfcA0HSaqajtBaHg)  |   |
| 003 |   |   |   |   |   |

**Comment by 0N0thing** [comment]
这个需要怎么搞？有感兴趣的可以帮忙参与一下 😄

**Comment by LinuxSuRen** [comment]
> 这个需要怎么搞？有感兴趣的可以帮忙参与一下 😄

按照第一个帖子里描述的，可以参与视频剪辑、字幕剪辑、视频审核、视频录制等等，以及我们还没有解锁的其他可做的事情。想好要参与哪块了，直接留言会拉你入群。

**Comment by 0N0thing** [comment]
流水线使用的15个DSL那个吧，我认领下，但是没有具体说明是哪15个，这要看到时候需要讲哪些

**Comment by LinuxSuRen** [comment]
> 流水线使用的15个DSL那个吧，我认领下，但是没有具体说明是哪15个，这要看到时候需要讲哪些

好的，那你新建一个类似于 https://github.com/jenkins-zh/jenkins-zh/issues/368 的 issues 来跟踪任务

**Comment by p00287621** [comment]
你好，我想录制：14 基于 Jenkins 构建 Helm chart，15 Jenkins 安装 SSH 节点

**Comment by yJunS** [comment]
@perrypeng-peng p00287621是你的id吗？ 如果是的话，还是修改成你的GitHub ID。这样方便定位

**Comment by perrypeng-peng** [comment]
@yJunS  就用这个perrypeng-peng即可。多谢。

**Comment by cizezsy** [comment]
认领 48, 49, 50, 51

**Comment by LinuxSuRen** [comment]
> 认领 48, 49, 50, 51

欢迎👏加入

**Comment by wyaopeng** [comment]
mark mark

**Comment by kklives** [comment]
认领 35, 36,41, 58

**Comment by LinuxSuRen** [comment]
> 认领 35, 36,41, 58

感谢加入我们团队，麻烦加以下社区微信 JenkinsInChina，并备注。我们会拉你进入视频录制微信群。
